# Generated by Django 4.1.3 on 2022-11-08 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('link', models.URLField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('author', models.URLField(blank=True, max_length=64, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ('-published_time',),
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(max_length=256, unique=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('link', models.URLField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(choices=[('updated', 'Updated'), ('error', 'Error')], default='updated', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ReadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rssfeedapi.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'read entry',
                'verbose_name_plural': 'read entries',
                'unique_together': {('user', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='FeedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_time', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rssfeedapi.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed')},
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', through='rssfeedapi.FeedSubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rssfeedapi.feed'),
        ),
        migrations.AddField(
            model_name='entry',
            name='read_by',
            field=models.ManyToManyField(related_name='read_entries', through='rssfeedapi.ReadEntry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['feed_url'], name='feed_url index'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['guid'], name='entry guid index'),
        ),
    ]
